# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title mode
#' @description The function calculates a mode of a given integer vector
#'
#' @param x IntegerVector
#' @return Integer value - mode of a vector
#'
#' @export
mode <- function(x) {
    .Call('bbhw6_mode', PACKAGE = 'bbhw6', x)
}

#' @title ...
#' @description ...
#'
#' @param min ...
#' @param max ....
#' @return ....
#'
#' @export
test <- function(min = 0.0, max = 1.0) {
    .Call('bbhw6_test', PACKAGE = 'bbhw6', min, max)
}

