# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title mode
#' @description The function calculates a mode of a given integer vector
#'
#' @param x IntegerVector
#' @return Integer value - mode of a vector
#'
#' @export
mode <- function(x) {
    .Call('bbhw6_mode', PACKAGE = 'bbhw6', x)
}

#' @title perms
#' @description The function generates all possible combinations of a given vector
#'
#' @param x input vector
#' @return Matrix - the matrix that represents all possible permutations
#'
#' @export
perms <- function(x) {
    .Call('bbhw6_perms', PACKAGE = 'bbhw6', x)
}

#' @title simplify2array
#' @description The function simplifies a list of numeric vectors into a numeric vector
#'
#' @param x List - expecting a list of numeric vectors
#' @return NumericVector - a list of numeric vectors
#'
#' @export
simplify2array <- function(x) {
    .Call('bbhw6_simplify2array', PACKAGE = 'bbhw6', x)
}

